workspace:
  base: /go
  path: src/github.com/zottelchin/Votierungstracker
pipeline:
  backend:
    image: golang
    commands:
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure
    - CGO_ENABLED=1 GOOS=linux go build -a -ldflags '-extldflags "-static" -s' -installsuffix cgo -o Votierungstracker -v .
  frontend:
    image: node
    commands:
    - cd frontend
    - npm install
    - npm run build
  publish:
    image: plugins/docker
    repo: zottelchin/votierungstracker
    tags: latest
    dockerfile: Dockerfile-CI
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
  deploy:
    image: plugins/webhook
    secrets: [ webhook_urls ]
    when:
      branch: master
